server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://119.23.68.211:9411
    sleuth:
      sampler:
        #采样值介于0到1中间,1表示全部采集
        probability: 1  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: gwall_test
    password: Gwall_test_0bug
    url: jdbc:mysql://g3-test-ww.mysql.zhangbei.rds.aliyuncs.com:3306/G_901_base?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    instance-id: payment8001
    prefer-id-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位位秒(默认30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到自后一次心跳后等待时间上线，单位位秒(默认90秒)超时将剔除服务
    lease-expiration-duration-in-seconds: 2
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    fetch-registry: true    
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要以来这个地址
      #defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/
      defaultZone: http://eureka-server7001.com:7001/eureka/
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.atguigu.springcloud.entites
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*.xml
