server:
  port: 7001
eureka:
  instance:
    hostname: eureka-server7001.com #eurka服务端实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要以来这个地址 ,集群是指向其它eureka
      #defaultZone: http://eureka-server7002.com:7002/eureka/
      #单机指向自己
      defaultZone: http://eureka-server7001.com:7001/eureka/
  server:
    #关闭自我保护机制,保护不可用服务及时剔除
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 2000