server:
  port: 1234
spring:
  application:
    name: cloud-config-center
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/pengxu38/springcloud-config.git
          username: 418299770@qq.com
          password: xp418299770
       search-paths:
         - springcloud-config
    label: master     
eureka:
  instance:
    hostname: eureka-server7001.com #eurka服务端实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/
  server:
    #关闭自我保护机制,保护不可用服务及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000